### PR TITLE
Update single_cell.md

### PR DESCRIPTION
**Pull request by PPerdomoQ**

### CODE REVIEW

**Comment by PPerdomoQ** [comment]
Add new rdf image

**Comment by NuriaQueralt** [comment]
Dear @PPerdomoQ, I reviewed your changes and I saw a couple of minor things: could you add an obo class for the :mouse_ instance? could you change the instance name :float_ for something more meaningful such as :unit_? Please modify these two minor things and ping me for review the PR again. Thank you.

**Comment by NuriaQueralt** [comment]
Dear @PPerdomoQ, the .md file needs some changes since the output representation of raw and normalized counts is not correct: the count values should not be a string, but an integer/float; the units should not be instanciated just use the appropriate UO unit class directly in the triple such as obo:UO_XXXXXXX; note that normalized_unit or raw_unit does not make sense, so remove obo:NCIT_C181341. Once this is done ping me again to review and reply this conversation thread. Thank you.

**Comment by PPerdomoQ** [comment]
Dear @NuriaQueralt, shouldn't the unit be instanciated such as the [EJPRD lab measurement](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/develop/docs/DCDE_lab_measurement.md)? Also, why doesn't the molecule count/normalized count make sense? Shouldn't this be specified to distinguish the units of both outputs?

**Comment by NuriaQueralt** [comment]
> Dear @NuriaQueralt, shouldn't the unit be instanciated such as the [EJPRD lab measurement](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/develop/docs/DCDE_lab_measurement.md)? 

Yes that is correct! my fault. Data is in one layer and semantics in another layer :)

> Also, why doesn't the molecule count/normalized count make sense? Shouldn't this be specified to distinguish the units of both outputs?

Maybe I misunderstood it. Are the units for normalized counts different to the units for raw counts?

**Comment by PPerdomoQ** [comment]
> Maybe I misunderstood it. Are the units for normalized counts different to the units for raw counts?

So in the molecule count (raw) you just have the actual number of RNA molecules of a certain gene, expressed as an integer (ie. 1000 molecules of dystrophin). In the normalized case you have a normalized value, which is different from the number of molecules, expressed as a float (ie. the expression of dystrophin is 0.63, which is more like a unitless value, similar to a percentage). So in the end in both cases you are expressing the number of molecules found, but I thought that it would be useful to distinguish the normalized one by adding obo:NCIT_C181341.

**Comment by NuriaQueralt** [comment]
> > Maybe I misunderstood it. Are the units for normalized counts different to the units for raw counts?
> 
> So in the molecule count (raw) you just have the actual number of RNA molecules of a certain gene, expressed as an integer (ie. 1000 molecules of dystrophin). In the normalized case you have a normalized value, which is different from the number of molecules, expressed as a float (ie. the expression of dystrophin is 0.63, which is more like a unitless value, similar to a percentage). So in the end in both cases you are expressing the number of molecules found, but I thought that it would be useful to distinguish the normalized one by adding obo:NCIT_C181341.

Then, I would suggest to add the 'normalized' semantics, i.e., NCIT_C181341, to the :normalized_ output instance because it is a feature of the output and not of the unit, and ensure what is the unit for this normalized data and add the corresponding unit from UO, whether is 'molecule count', or 'percentage'. How does this sound?

**Comment by PPerdomoQ** [comment]
> How does this sound?

Sounds great :) I'll change it then

**Comment by PPerdomoQ** [comment]
@NuriaQueralt I think everything should be changed by now :)

**Comment by NuriaQueralt** [comment]
> @NuriaQueralt I think everything should be changed by now :)

Perfect @PPerdomoQ please merge the PR :+1:

**Pull request merged**
